# Generated by Django 4.0.2 on 2022-03-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_orderitem_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipingPrice',
            new_name='shippingPrice',
        ),
    ]
