# Generated by Django 4.0.2 on 2022-03-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_shipingprice_order_shippingprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipingAddress',
            new_name='ShippingAddress',
        ),
    ]
